import Head from "next/head";
import Header from "../../components/header/index";
import Me from "../../components/me/Me";

export default function UserProfile() {
  return (
    <div>
      <Head>
        <title>React playground</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Me />
    </div>
  );
}
