import Head from "next/head";
import Header from "../../components/header";
import Profile from "../../components/profile/Profile";
import CenteredLayout from "../../components/layout/centeredLayout";

export default function ProfilePage() {
  return (
    <div>
      <Head>
        <title>React playground</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <CenteredLayout>
        <h1>See posts you might be interested</h1>
      </CenteredLayout>
    </div>
  );
}
