import Head from "next/head";
import Header from "../components/header";
import Link from "next/link";

import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["common"])),
      // Will be passed to the page component as props
    },
  };
}

export default function Home() {
  const { t, i18n } = useTranslation("common");
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="homepage-layout">
        <div>
          <Link href="/signin">{t("to-signin-page")}</Link>
        </div>
        <div>
          <Link href="/signup">{t("to-signup-page")}</Link>
        </div>
      </div>
    </div>
  );
}
