import Head from "next/head";
import Header from "../components/header";
import Editable from "../components/editable";

export default function textEditor() {
  return (
    <div>
      <Head>
        <title>React playground</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Editable />
    </div>
  );
}
